#! /bin/bash

source $(dirname $0)/config

while read -r line ; do
    case $line in
        S*)
            sys_infos="%{r}${line#?}"
            ;;
        T*)
            title="%{c}${line#?}"
            ;;
        W*)
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                if ! [[ $name =~ "INVIS" ]]; then
                    case $item in
                        [OFU]*)
                            # active desktop
                            wm_infos="$wm_infos %{F$COLOR_ACTIVE}$name%{F-}"
                            ;;
                        o*)
                            # inactive but occupied desktop
                            wm_infos="$wm_infos %{F$COLOR_OCCUPIED}$name%{F-} "
                            ;;
                        u*)
                            # urgent desktop
                            wm_infos="$wm_infos %{F$COLOR_URGENT}$name%{F-} "
                            ;;
                    esac
                fi
                shift
            done
            ;;
    esac
    printf "%s\n" "$wm_infos$title$sys_infos"
done
