#! /bin/bash

level() {
    amixer get Master | sed -n 's/^.*\[\([0-9]\+\)%.*$/\1/p' | uniq
}

state() {
    amixer get Master | sed -n 's/^.*\[\(o[nf]\+\)]$/\1/p' | uniq
}

if [[ `state` == on ]]; then
    icon="on"
else
    icon="%{F#FFFF0000}off%{F-}"
fi

echo -n "Volume: $icon `level`"
