#!/bin/sh

wid=$1
class=$2
instance=$3

# echo "WID: $wid CLASS: $class INSTANCE: $instance" >> /tmp/extern.log


# Chrome popups
if [ -z "$class" -a -z "$instance" ]; then
    echo "floating = on"
fi
