#!/bin/sh
xrdb -merge ~/.Xresources &
xset fp rehash
xsetroot -cursor_name left_ptr &

# set key board repeat rate
xset r rate 200 40 &
xmodmap ~/.xmodmap &
hsetroot -fill /home/ryan/drive/pics/wallpapers/arch-linux-rainbow-solarized.png &

eval $(gpg-agent --daemon) &

sxhkd -f 20 &
exec bspwm
