#!/bin/zsh

if [[ $TERM == "xterm-termite" ]] ; then
    eval "$(keychain --agents ssh --eval -Q --quiet ~/.ssh/id_rsa)"
fi

# By default, zsh considers many characters part of a word (e.g., _ and -).
# Narrow that down to allow easier skipping through words via M-f and M-b.
export WORDCHARS='*?[]~&;!$%^<>'

export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/.tmuxifier/bin
export PATH=$PATH:/opt/android-sdk/platform-tools
export PATH=$PATH:/usr/local/heroku/bin
export PATH=$PATH:~/.rvm/bin
export PATH=$PATH:~/.cabal/bin

export EDITOR=vim
export BROWSER=chrome

export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/projects
export VIRTUALENVWRAPPER_PROJECT_FILENAME=.venv
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
source /usr/bin/virtualenvwrapper.sh

# tmux
export TMUXIFIER_LAYOUT_PATH=~/.tmuxifier_layouts

# bspwm
export PANEL_FIFO=/tmp/panel-fifo
export PANEL_HEIGHT=24
export PANEL_FONT_FAMILY="-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1"
export BSPWM_SOCKET=/tmp/bspwm-socket
export SXHKD_SHELL=/bin/bash

export CATALINA_HOME=/opt/apache-tomcat
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk

unset GREP_OPTIONS

eval "$(tmuxifier init -)"
eval "$(dircolors ~/.dir_colors/dircolors.256dark)"
eval "$(fasd --init posix-alias zsh-hook)"
