#!/bin/zsh
# Env setup. Done here instead of .zshenv because /etc/profile overwrites stuff
if [[ $TERM == "xterm-termite" ]] ; then
    eval "$(keychain --agents ssh --eval -Q --quiet ~/.ssh/id_rsa)"
fi

# By default, zsh considers many characters part of a word (e.g., _ and -).
# Narrow that down to allow easier skipping through words via M-f and M-b.
export WORDCHARS='*?[]~&;!$%^<>'

export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/.tmuxifier/bin
export PATH=$PATH:/opt/android-sdk/platform-tools
export PATH=$PATH:/usr/local/heroku/bin
export PATH=$PATH:~/.rvm/bin
export PATH=$PATH:~/.cabal/bin

export EDITOR=vim
export BROWSER=chrome

export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/projects
export VIRTUALENVWRAPPER_PROJECT_FILENAME=.venv
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
source /usr/bin/virtualenvwrapper.sh

# tmux
export TMUXIFIER_LAYOUT_PATH=~/.tmuxifier_layouts

# bspwm
export PANEL_FIFO=/tmp/panel-fifo
export PANEL_HEIGHT=24
export PANEL_FONT_FAMILY="-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1"
export BSPWM_SOCKET=/tmp/bspwm-socket
export SXHKD_SHELL=/bin/bash

export CATALINA_HOME=/opt/apache-tomcat
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk

unset GREP_OPTIONS

eval "$(tmuxifier init -)"
eval "$(dircolors ~/.dir_colors/dircolors.256dark)"
eval "$(fasd --init posix-alias zsh-hook)"


# Auto completion
zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' '+l:|=* r:|=*'  # Complete from middle of words
autoload -U compinit
compinit

# Prompt
autoload -U promptinit colors && promptinit && colors
setopt promptsubst
source ~/.zsh_themes/ryan.zsh-theme

# Syntax highlighting
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# History
HISTFILE=~/.zsh_history
SAVEHIST=20000
HISTSIZE=20000
setopt extended_history
setopt inc_append_history

# Use emacs key bindings.
bindkey -e

# Filter based on what is already typed.
# bindkey "^P" history-beginning-search-backward
# bindkey "^N" history-beginning-search-forward
bindkey "^P" up-line-or-search
bindkey "^N" down-line-or-search

# Automaticly activate virtualenvs
auto_venv() {
    if [ -e .venv ]; then
        if [ "$(cat .venv)" != "$(basename "$VIRTUAL_ENV")" ]; then
            workon "$(cat .venv)"
        fi
    fi
}
add-zsh-hook chpwd auto_venv

alias ls="ls --color=auto"
alias tmux="tmux -2"
alias ssh='TERM=xterm ssh'  # Nobody knows about poor termite...

alias at="tmux attach -t "
alias load="tmuxifier load-session "
alias v='f -e vim'
alias c='fasd_cd -d'

alias sc-start="sudo systemctl start"
alias sc-restart="sudo systemctl restart"
alias sc-stop="sudo systemctl stop"
