#!/bin/zsh

# Auto completion
zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' '+l:|=* r:|=*'  # Complete from middle of words
autoload -U compinit
compinit

# Prompt
autoload -U promptinit colors && promptinit && colors
setopt promptsubst
source ~/.zsh_themes/ryan.zsh-theme

# Syntax highlighting
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# History
HISTFILE=~/.zsh_history
SAVEHIST=20000
HISTSIZE=20000
setopt extended_history
setopt inc_append_history

# Use emacs key bindings.
bindkey -e

# Filter based on what is already typed.
# bindkey "^P" history-beginning-search-backward
# bindkey "^N" history-beginning-search-forward
bindkey "^P" up-line-or-search
bindkey "^N" down-line-or-search

# Automaticly activate virtualenvs
auto_venv() {
    test -e .venv && workon "$(cat .venv)"
}
add-zsh-hook chpwd auto_venv

alias ls="ls --color=auto"
alias tmux="tmux -2"
alias ssh='TERM=xterm ssh'  # Nobody knows about poor termite...

alias at="tmux attach -t "
alias load="tmuxifier load-session "
alias v='f -e vim'
alias c='fasd_cd -d'

alias sc-start="sudo systemctl start"
alias sc-restart="sudo systemctl restart"
alias sc-stop="sudo systemctl stop"
